spring:
  kafka:
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: localhost:9092
    consumer:
      group-id: '1'
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    redis:
      host: localhost
      port: '6379'
    mongodb:
      database: jn26-auth-db
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: 'true'
    tags:
      application: ${spring.application.name}
  otlp:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: '1.0'
auth-service:
  portnumber: '8091'
  hostname: localhost
logging:
  level:
    org:
      springframework: info
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
zipkin:
  baseUrl: http://localhost:9411
server:
  port: '8098'
eureka:
  client:
    registerWithEureka: 'true'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: 'true'
  instance:
    preferIpAddress: 'true'
service:
  name: auth-service

#service.name= auth-service
#server.port=8098
#
#spring.data.mongodb.database=jn26-auth-db
#
#logging.level.org.springframework=info
#
## For a local Redis instance
#spring.data.redis.host=localhost
#spring.data.redis.port=6379
#
#auth-service.hostname=localhost
#auth-service.portnumber=8091
#
#
## All traces should be sent to latency analysis tool
#management.tracing.sampling.probability=1.0
#management.otlp.tracing.endpoint=http://localhost:9411/api/v2/spans
##management.endpoints.web.exposure.include=prometheus
#
## For Exemplars to work we need histogram buckets
#management.metrics.distribution.percentiles-histogram.http.server.requests=true
#
## traceID and spanId are predefined MDC keys - we want the logs to include them
#logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
#
#eureka.instance.preferIpAddress= true
#eureka.client.registerWithEureka= true
#eureka.client.fetchRegistry= true
#eureka.client.serviceUrl.defaultZone= http://localhost:8761/eureka
#
#spring.kafka.consumer.bootstrap-servers= localhost:9092
#spring.kafka.consumer.group-id= 1
#spring.kafka.consumer.auto-offset-reset=earliest
#spring.kafka.consumer.key-deserializer= org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer= org.apache.kafka.common.serialization.StringDeserializer
#
#spring.kafka.producer.bootstrap-servers= localhost:9092
#spring.kafka.producer.key-serializer= org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer= org.apache.kafka.common.serialization.StringSerializer
#
#
#zipkin.baseUrl: http://localhost:9411
#
#management.endpoints.web.exposure.include= health, metrics, prometheus
#management.metrics.tags.application=${spring.application.name}
