spring:
  kafka:
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: localhost:9092
    consumer:
      group-id: '1'
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    redis:
      host: localhost
      port: '6379'
    mongodb:
      database: auth-db
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: 'true'
    tags:
      application: ${spring.application.name}
  otlp:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: '1.0'
auth-service:
  portnumber: '8091'
  hostname: localhost
logging:
  level:
    org:
      springframework: info
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
zipkin:
  baseUrl: http://localhost:9411
server:
  port: '8098'
eureka:
  client:
    registerWithEureka: 'true'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: 'true'
  instance:
    preferIpAddress: 'true'
service:
  name: auth-service